import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const inter = Inter({ subsets: ["latin", "latin-ext"] });

// Used by Next to resolve relative URLs in metadata (og:image, twitter:image,
// apple-touch-icon) into absolute URLs at build time. Set
// NEXT_PUBLIC_SITE_URL to your deployed origin (e.g. the pages.dev URL or a
// custom domain). Falls back to localhost for dev so unfurl previews don't
// crash with an invalid URL.
const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "itinly",
  description:
    "Your flight, hotel, and reservation emails, automatically organized into a day-by-day trip plan.",
  // Declare icons explicitly so the rendered <link> tags advertise the
  // right sizes. Without this, Next's auto-discovery of `app/favicon.ico`
  // emits sizes="16x16" only — Google's favicon picker requires ≥ 48×48
  // and silently skips anything smaller. The SVG carries sizes="any" so
  // crawlers treat it as the canonical, scalable icon.
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml", sizes: "any" },
      { url: "/favicon.ico", sizes: "48x48 32x32 16x16" },
    ],
    // Point at the PNG route generated by `app/apple-icon.tsx`. We
    // declare it explicitly here rather than relying on Next's
    // file-convention auto-detection because the auto-emitted tag
    // wasn't reliably appearing in the head in dev (and the failure
    // mode is silent — iOS just falls back to a screenshot of the
    // page, which is what was producing the "white vertical line"
    // home-screen icon).
    apple: [
      { url: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  },
  openGraph: {
    title: "itinly",
    description:
      "Your flight, hotel, and reservation emails, automatically organized into a day-by-day trip plan.",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "itinly",
    description:
      "Your flight, hotel, and reservation emails, automatically organized into a day-by-day trip plan.",
  },
  // Tells iOS Safari this site can run as a standalone PWA — strips the
  // browser chrome when launched from the home screen and uses the right
  // status-bar style. Android / Chromium picks this up from the
  // webmanifest already.
  appleWebApp: {
    capable: true,
    title: "itinly",
    statusBarStyle: "default",
  },
};

// Theme color drives the Android task-switcher card, the desktop PWA
// titlebar, and the iOS Safari URL bar tint. Keep in sync with
// manifest.ts.
export const viewport: Viewport = {
  themeColor: "#18181b",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  return (
    // suppressHydrationWarning is required by next-themes — the provider sets
    // a `class` and `style` on <html> before React hydrates so the page
    // doesn't flash the wrong theme, which would otherwise trip React's
    // hydration mismatch warning.
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>{children}</Providers>
        {/* top-center keeps toasts from overlapping the top-right header
            controls (avatar, share button, action pills) on the mobile
            trip page where vertical space is tight. */}
        <Toaster richColors position="top-center" />
        {/* Vercel Web Analytics. Auto-detects mode — fires only in
            production deployments, no-op in local dev / preview unless
            VERCEL_ANALYTICS_ID is set. Cookieless and PII-free by default. */}
        <Analytics />
        {/* Vercel Speed Insights. Reports Core Web Vitals (LCP, FID, CLS)
            from real users on production deployments. Same auto-detection
            as Analytics — no-op outside Vercel production. */}
        <SpeedInsights />
      </body>
    </html>
  );
}
