import type { MetadataRoute } from "next";

/**
 * Web app manifest. Lets the site be added to a phone's home screen
 * with the brand icon (treasure-map with destination pin) instead of a
 * generic screenshot.
 */
export const dynamic = "force-static";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "itinly",
    short_name: "itinly",
    description:
      "Your flight, hotel, and reservation emails, automatically organized into a day-by-day trip plan.",
    // Land installed users in the mobile shell — that's the experience
    // tuned for phone use. The auto-redirect from `/` would also work but
    // adds a flicker on every cold launch.
    start_url: "/m",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#F8F9FA",
    // Primary navy from palette A — drives the Android task-switcher card,
    // desktop PWA titlebar, and iOS Safari URL-bar tint. Keep in sync with
    // the Viewport export in app/layout.tsx.
    theme_color: "#1A2B3C",
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      // 180×180 PNG generated by `app/apple-icon.tsx`. Listed here so
      // Android's PWA install path has a raster fallback (it'll prefer
      // the SVG, but some launchers prefer raster). iOS reads the
      // `<link rel="apple-touch-icon">` tag emitted automatically from
      // the same file, not this manifest entry.
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
