import type { MetadataRoute } from "next";

/**
 * Web app manifest. Lets the site be added to a phone's home screen
 * with the brand icon (treasure-map with destination pin) instead of a
 * generic screenshot.
 *
 * The name is suffixed on Vercel preview deployments so a preview
 * install doesn't get confused with the production app on the same
 * device — both can sit on the home screen labelled "itinly preview"
 * vs "itinly". `VERCEL_ENV` is set per-deploy by Vercel (`production`,
 * `preview`, or `development`) and is available at build time since
 * this manifest is force-static.
 */
export const dynamic = "force-static";

export default function manifest(): MetadataRoute.Manifest {
  const isPreview = process.env.VERCEL_ENV === "preview";
  const name = isPreview ? "itinly preview" : "itinly";
  // Home-screen launchers truncate around 12 chars — keep short_name
  // tight so the suffix doesn't get clipped mid-word on Android.
  const shortName = isPreview ? "itinly·prev" : "itinly";

  return {
    name,
    short_name: shortName,
    description:
      "Your flight, hotel, and reservation emails, automatically organized into a day-by-day trip plan.",
    // Land installed users in the mobile shell — that's the experience
    // tuned for phone use. The auto-redirect from `/` would also work but
    // adds a flicker on every cold launch.
    start_url: "/m",
    scope: "/",
    display: "standalone",
    // Let the installed PWA rotate with the device. The mobile shell is
    // tuned for portrait but we don't want to forbid landscape — phones in
    // a car mount, tablets, and accessibility setups all benefit from
    // following the OS rotation.
    orientation: "any",
    background_color: "#F8F9FA",
    // Primary navy from palette A — drives the Android task-switcher card,
    // desktop PWA titlebar, and iOS Safari URL-bar tint. Keep in sync with
    // the Viewport export in app/layout.tsx.
    theme_color: "#1A2B3C",
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      // 180×180 PNG generated by `app/apple-icon.tsx`. Listed here so
      // Android's PWA install path has a raster fallback (it'll prefer
      // the SVG, but some launchers prefer raster). iOS reads the
      // `<link rel="apple-touch-icon">` tag emitted automatically from
      // the same file, not this manifest entry.
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
    // Register the installed PWA as an OS-level share target so users
    // can hit Share in Mail / Gmail / Safari / messaging apps and pick
    // "itinly" — that bypasses the Gmail-scan ceremony for one-off
    // bookings and unblocks non-Gmail mailboxes on the go. The receiver
    // page at /m/share reads the three query params below and feeds
    // them through the same parser pipeline as the email-scan flow.
    //
    // GET (rather than POST + multipart) is sufficient for our needs —
    // every meaningful share intent (selected email body as `text`, a
    // confirmation page as `url`, the subject line as `title`) is
    // representable as query params, and GET also keeps the SW's
    // network-first navigation handler in play instead of needing a
    // POST-specific fetch branch. File-based shares (e.g. forwarded
    // .eml) are a follow-up.
    share_target: {
      action: "/m/share",
      method: "GET",
      enctype: "application/x-www-form-urlencoded",
      params: {
        title: "title",
        text: "text",
        url: "url",
      },
    },
    // PWA app-icon shortcuts (Android long-press, desktop right-click).
    // Each entry adds a quick action straight from the home screen so
    // common flows skip the trip list. "Create trip" deep-links into
    // `/m` with `?new=trip`; the trip-list page reads that on mount,
    // pops the MobileCreateTripSheet open, then scrubs the param out
    // of the URL so a refresh or back-nav doesn't re-trigger it.
    shortcuts: [
      {
        name: "Create trip",
        short_name: "New trip",
        description: "Start a new trip with a name and date range",
        url: "/m?new=trip",
      },
    ],
  };
}
